[package]
name = "monoruby"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.8.0"
ariadne = "0.1.3"
rustyline = "9.1.2"
monoasm_macro = { path = "../monoasm/monoasm_macro" }
monoasm = { path = "../monoasm/monoasm" }